--liquibase formatted sql

/* Add baseline tag for DB */

--changeset TAG:BASELINE

UPDATE testdb.DATABASECHANGELOG
SET TAG='BASELINE'
WHERE DATEEXECUTED=(SELECT MAX(DATEEXECUTED) FROM DATABASECHANGELOG);
--ROLLBACK DELETE FROM DATABASECHANGELOG WHERE AUTHOR='TAG' AND ID='BASELINE';